##########################################################
##       !!! WARNING, DO NOT EDIT THIS FILE !!!         ##
##         Auto-generated file python bindings.         ##
##########################################################
from .lib import lib # Amazing naming creativity..
zig_add = lib.zig_add